##############################################
# +----------------------------------------+ #
# |               Explosions               | #
# +----------------------------------------+ #
##############################################

# This section covers all the explosion tweaks for PvP.

end-crystals:
  # Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
  # The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

##############################################
# +----------------------------------------+ #
# |                Hostility               | #
# +----------------------------------------+ #
##############################################

hostility-colour-stages:
  0: '#E6850B'
  1: '#E6850B'
  2: '#E6850B'
  3: '#E6850B'
  4: '#E6850B'
  5: '#E6850B'
  6: '#EE7878'
  7: '#EE7878'
  8: '#EF6A6A'
  9: '#EF5959'
  10: '#EF4949'
  11: '#E73B3B'
  12: '#E73B3B'
  13: '#E73B3B'
  14: '#CF2929'
  15: '#CF2929'
  16: '#B12323'
  17: '#982020'
  18: '#861D1D'
  19: '#6E1717'
  20: '#541111'
  21: '#360B0B'

##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  prefix: "§c§lU§f§lL §7§lCombat §8§l» "
  reload: "§2Plugin reloaded."
  invalid-command: "§cInvalid command usage."
  no-permission: '§2You don''t have permission to perform this command.'
  help-message:
    - '§l§cUnited §fCombat'
    - '§8/pvp degrade [On/Off] §7Toggle hostility decrease every new Towny day.'
    - '§8/pvp status §7Show your current status and hostility points.'
    - '§8/pvp on §7Disable your new player immunity.'
  in-combat: '§cYou can''t use that command while in combat!'
  pvp-disabled: '§cPvP disabled!'
  pvp-enabled: '§aPvP enabled.'
  pvp-degrade-enabled: '§aEnabled hostility degradation.'
  pvp-degrade-disabled: '§cDisabled hostility degradation.'
  player-not-recognised: '§cPlayer not found.'
  pvp-status: '§7Your current status is §e§l<status>§7, and you have §e§l<hostility> §7hostility points.'
  you-are-immune: '§cYou are immune for §e§l<time>. §7Please do §8/pvp on §cto attack this player!'
  target-immune: '§cPlayer is new is immune to attacks!'
  immunity-removed: '§cYou are no longer immune to attacks, and can attack other players!'
  you-are-not-immune: '§cYou are not immune to attacks!'
  kicked-out-of-neutrality-mayor: '§cYour town is no longer neutral! You cannot change this as long as you have hostile residents in your town.'
  kicked-out-of-neutrality-king: '§cYour nation is no longer neutral! You cannot change this as long as you have hostile towns in your nation!'
  cannot-be-neutral: '§cYou cannot toggle your town neutrality! You have hostile players in your town, found players: §e§l<players>§c. You can mute this message using §8/pvp mute§7.'
  cannot-be-neutral-nation: '§cYou cannot toggle your nation neutrality! You have hostile towns in your nation, found towns: §e§l<towns>§c. You can mute this message using §8/pvp mute§7.'
  muted-notif: '§cNeutrality warning notifications have been muted! Run §8/pvp mute §cagain to unmute.'
  unmuted-notif: '§aNeutrality warning notifications unmuted! Run §8/pvp mute §ato mute them again.'
  kicked-out-of-neutrality: '§cYour town has lost neutrality due to your actions!'