name: UnitedCombat
version: '${project.version}'
main: org.unitedlands.pvp.UnitedCombat
api-version: 1.17
authors: [ Maroon28 ]
depend: [ Towny ]
softdepend: [ PlaceholderAPI ]
commands:
  pvp:
     description: Main PVP command. Used to enable and disable pvp status.
     usage: /pvp on | off | status [player]