name: UnitedCombat
version: '3.0.5'
main: org.unitedlands.combat.UnitedCombat
api-version: 1.21
authors: [Maroon28]
contributors: [Litning11, Theriel_]
depend: [ Towny ]
softdepend: [ PlaceholderAPI ]
commands:
  unitedcombat:
    description: Reloads the plugin config.
    usage: /unitedcombat reload
    permission: united.combat.admin
  pvp:
     description: Main PVP command. Used to enable and disable pvp status.
     usage: /pvp on | off | status [player]