name: UnitedCombat
version: '3.0.0'
main: org.unitedlands.pvp.UnitedCombat
api-version: 1.21
authors: [Maroon28]
contributors: [Litning11, Theriel_]
depend: [ Towny ]
softdepend: [ PlaceholderAPI ]
commands:
  pvp:
     description: Main PVP command. Used to enable and disable pvp status.
     usage: /pvp on | off | status [player]